# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-15 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20200115_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile_user',
            new_name='profile',
        ),
    ]
