# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-15 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_auto_20200115_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
