# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-15 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_remove_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='screenshot_four',
        ),
        migrations.RemoveField(
            model_name='post',
            name='screenshot_three',
        ),
    ]
